version: 2.1
jobs:
  build:
    working_directory: ~/docker-superset
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
         version: 17.05.0-ce
         docker_layer_caching: true

      - run:
         name: list files
         command: ls -lsrt ~/docker-superset

      - run:
         name: Build Docker image
         command: docker build -t abhioncbr/docker-superset:$IMAGE_VERSION --build-arg SUPERSET_VERSION=$SUPERSET_VERSION -f ~/docker-superset/docker-files/Dockerfile .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push abhioncbr/docker-superset:$IMAGE_VERSION

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop